[package]
name = "shipwreck"
version = "0.1.0"
edition = "2024"
description = "A silly, hilarious extravagance in personal CI/CD tooling that is delightfully excessive but will ultimately yield some reduced pain and, frankly, enjoyment."

[dependencies]
clap = { version = "4.5.33", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_yaml = "0.9"
serde_json = "1.0"
anyhow = "1.0"