# config.toml
# ------------------------------------------------------------
# User Plugin Configuration for this Make It So Plugin
# Users can (and should) modify this file according to plugin requirements.
# Access values in your plugin via `ctx.config.<key>`

# Sample config (used by the `moo` command):
message = "Make It So 🪄" # ctx.config.message

# --- Examples ---

# [my_section]                 # ctx.config.my_section
# my_key = "foo"               # ctx.config.my_section.my_key

# my_string = "hello world"    # String
# my_number = 42               # Number
# my_boolean = true            # Boolean
# my_list = ["item1", "item2", "item3"]  # List
