# manifest.toml
# -----------------------------
# Plugin Manifest for Make It So
# This file defines plugin metadata, permissions, CLI commands, and external dependencies.

# -----------------------------
# Plugin Metadata
# -----------------------------
[plugin]
name = "examples"
version = "0.1.0"
description = "A plugin scaffolded by Make It So."
registry = ""                                      # Optional: a remote registry or package endpoint

# -----------------------------
# Global Plugin Permissions
# These apply to all commands unless overridden individually.
# -----------------------------
[permissions]
file_read = []     # Paths your plugin can read from (e.g. ["./data"])
file_write = []    # Paths your plugin can write to (e.g. ["./logs"])
network = []       # Domains your plugin can access (e.g. ["api.github.com"])
run_commands = []  # Shell commands allowed to run (e.g. ["git", "npm"])
env_access = false # Allow reading environment variables

# -----------------------------
# CLI Commands
# Define each command with its own section.
# -----------------------------
[commands.moo]
# This is a scaffolded example command generated by `mis create`.
# You can remove or modify it as needed.
description = "Moo!!!!"
script = "./examples.ts" # Path to the script file executed for this command

# Optional CLI arguments
[commands.moo.args.optional]
message = { description = "Custom message to display", arg_type = "string" }

# Command-specific permissions (extends or overrides top-level)
[commands.moo.permissions]
network = ["cowsay-api.example.com"]
run_commands = ["cowsay"]

# -----------------------------
# External Deno Dependencies
# These are remote modules your plugin can import.
# -----------------------------
[deno_dependencies]
cowsay = "https://deno.land/x/cowsay@1.1/mod.ts"
# chalk = "https://deno.land/x/chalk@1.0/mod.ts"  # Example additional import
